title: Introduction to Data Science
author: Somerset NHS Foundation Trust
only_build_toc_files: true
logo: images/team_logo.png
execute:
  execute_notebooks: off
repository:
  url: https://github.com/SomersetNHSFoundationTrust/DataScienceCourse
html:
  use_repository_button: true
  favicon: images/favicon.ico
  extra_footer: '<div><img src="trust_logo.png" alt="Somerset NHS Foundation Trust Logo" style="width: 50px; height: auto;"/><span>&copy; Somerset NHS Foundation Trust 2023</span></div>'
launch_buttons:
  colab_url: "https://colab.research.google.com"
sphinx:
  config:
    html_show_copyright: false
    html_extra_path: [ 'Content/_static' ]
