title: Data Science Basics
author: SomersetFT
only_build_toc_files: true
logo: images/team_logo.png
copyright: "2023"
execute:
  execute_notebooks: off
repository:
  url: https://github.com/SomersetNHSFoundationTrust/DataScienceCourse
html:
  use_repository_button: true
  favicon: images/favicon.ico